player_limit: -1
permissions:
  default:
  - bungeecord.command.service
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
timeout: 30000
log_commands: false
online_mode: true
disabled_commands:
- disabledcommandhere
servers:
  Lobby-1:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
listeners:
- query_port: 25577
  motd: '&bCloud Network Environment Technology &cBungeeCord drop server'
  priorities:
  - Lobby-1
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
ip_forward: true
network_compression_threshold: 256
groups: { }
connection_throttle: -1
stats: 13be5ac9-5731-4502-9ccc-c4a80163f14a
prevent_proxy_connections: false
